import { FormEvent, useEffect, useState } from 'react';
import { api } from './api';
import type { Pessoa, Totais, Transacao, TipoTransacao } from './types';

const moeda = new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' });
export default function App() {
  const [pessoas, setPessoas] = useState<Pessoa[]>([]); const [transacoes, setTransacoes] = useState<Transacao[]>([]); const [totais, setTotais] = useState<Totais>();
  const [erro, setErro] = useState(''); const [nome, setNome] = useState(''); const [idade, setIdade] = useState('');
  const [descricao, setDescricao] = useState(''); const [valor, setValor] = useState(''); const [tipo, setTipo] = useState<TipoTransacao>('Despesa'); const [pessoaId, setPessoaId] = useState('');
  const carregar = async () => { try { const [ps, ts, tt] = await Promise.all([api.listarPessoas(), api.listarTransacoes(), api.totais()]); setPessoas(ps); setTransacoes(ts); setTotais(tt); if (!pessoaId && ps[0]) setPessoaId(ps[0].id); } catch { setErro('Não foi possível conectar à API. Confirme que o back-end está em execução.'); } };
  useEffect(() => { carregar(); }, []);
  const salvarPessoa = async (e: FormEvent) => { e.preventDefault(); try { setErro(''); await api.criarPessoa(nome, Number(idade)); setNome(''); setIdade(''); await carregar(); } catch (e) { setErro((e as Error).message); } };
  const salvarTransacao = async (e: FormEvent) => { e.preventDefault(); try { setErro(''); await api.criarTransacao(descricao, Number(valor), tipo, pessoaId); setDescricao(''); setValor(''); await carregar(); } catch (e) { setErro((e as Error).message); } };
  const excluir = async (pessoa: Pessoa) => { if (!confirm(`Excluir ${pessoa.nome} e todas as suas transações?`)) return; try { await api.excluirPessoa(pessoa.id); await carregar(); } catch (e) { setErro((e as Error).message); } };
  return <main><header><h1>Gastos residenciais</h1><p>Controle simples de receitas e despesas da casa.</p></header>{erro && <p className="erro">{erro}</p>}
    <section className="grid"><form onSubmit={salvarPessoa}><h2>Nova pessoa</h2><label>Nome<input required value={nome} onChange={e => setNome(e.target.value)} /></label><label>Idade<input required min="0" max="150" type="number" value={idade} onChange={e => setIdade(e.target.value)} /></label><button>Adicionar pessoa</button></form>
    <form onSubmit={salvarTransacao}><h2>Nova transação</h2><label>Descrição<input required value={descricao} onChange={e => setDescricao(e.target.value)} /></label><label>Valor<input required min="0.01" step="0.01" type="number" value={valor} onChange={e => setValor(e.target.value)} /></label><label>Tipo<select value={tipo} onChange={e => setTipo(e.target.value as TipoTransacao)}><option value="Despesa">Despesa</option><option value="Receita">Receita</option></select></label><label>Pessoa<select required value={pessoaId} onChange={e => setPessoaId(e.target.value)}><option value="">Selecione</option>{pessoas.map(p => <option key={p.id} value={p.id}>{p.nome} ({p.idade} anos)</option>)}</select></label><button disabled={!pessoas.length}>Adicionar transação</button></form></section>
    <section><h2>Pessoas</h2><table><thead><tr><th>Nome</th><th>Idade</th><th></th></tr></thead><tbody>{pessoas.map(p => <tr key={p.id}><td>{p.nome}</td><td>{p.idade}</td><td><button className="danger" onClick={() => excluir(p)}>Excluir</button></td></tr>)}{!pessoas.length && <tr><td colSpan={3}>Nenhuma pessoa cadastrada.</td></tr>}</tbody></table></section>
    <section><h2>Consulta de totais</h2><table><thead><tr><th>Pessoa</th><th>Receitas</th><th>Despesas</th><th>Saldo</th></tr></thead><tbody>{totais?.pessoas.map(p => <tr key={p.pessoaId}><td>{p.nome}</td><td>{moeda.format(p.receitas)}</td><td>{moeda.format(p.despesas)}</td><td>{moeda.format(p.saldo)}</td></tr>)}<tr className="total"><td>Total geral</td><td>{moeda.format(totais?.totalReceitas ?? 0)}</td><td>{moeda.format(totais?.totalDespesas ?? 0)}</td><td>{moeda.format(totais?.saldoLiquido ?? 0)}</td></tr></tbody></table></section>
    <section><h2>Transações</h2><table><thead><tr><th>Descrição</th><th>Pessoa</th><th>Tipo</th><th>Valor</th></tr></thead><tbody>{transacoes.map(t => <tr key={t.id}><td>{t.descricao}</td><td>{t.pessoaNome}</td><td>{t.tipo}</td><td>{moeda.format(t.valor)}</td></tr>)}{!transacoes.length && <tr><td colSpan={4}>Nenhuma transação cadastrada.</td></tr>}</tbody></table></section></main>;
}
